project:
  type: website
  output-dir: docs

website:
  title: "Movement Science Course Demo"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pathways.qmd
      - all_modules.qmd
      - about.qmd
    tools:
      - icon: github
        href: https://github.com
      - icon: youtube
        href: https://youtube.com
      
    
      
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.md

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

